[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anilibria-rlib = {path = "../anilibria-rlib"}
tokio = { version = "1.0", features = ["full"] }